import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/ui/Navbar";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Navbar />
        {children}
        </body>
    </html>
  );
}
